name: Run nix-shell scripts
description: Executes shell scripts using nix-shell.

inputs:
  run:
    type: string
    required: true
    description: The path to a file that contains shell code or the actual shell code.
  options:
    type: string

runs:
  using: composite
  steps:
    - shell: bash
      env:
        RNS_OPTS: ${{ inputs.options }}
        RNS_RUN: ${{ inputs.run }}
      run: ${GITHUB_ACTION_PATH}/tools/run_nix_shell
