name: Run nix-shell scripts
description: Executes shell scripts using nix-shell.

inputs:
  run:
    type: string
    required: true
    description: The path to a file that contains shell code or the actual shell code.
  pure:
    type: boolean
    default: true
    description: Whether to run the script with the `--pure` option. Defaults to `true`.
  options:
    type: string
    description: Any parameters that are to be passed to nix-shell are specified here.
  working-directory:
    type: string
    description: |
      The path where nix-shell is executed and the script will be executed.
    default: .
  derivation-path:
    type: string
    description: |
      The path to a directory containing shell.nix or default.nix; or a path to a .nix file to
      use to set up the environment.

      Note, the path is resolved relative to the project root.
  shell-flags:
    type: string
    default: set -o errexit -o nounset -o pipefail
    description: These flags will be set before executing the script.
  verbose:
    type: boolean
    description: Enable debug output written to stderr.
    default: false

outputs:
  outputs:
    description: The outputs of the nix-shell-run

runs:
  using: node24                 # keep this in sync with @nodejs in MODULE.bazel
  main: dist/bundle.mjs
