name: Set up GitHub runner

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=./nixpkgs.nix
        extra_nix_config: |
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
          extra-substituters = https://cache.iog.io
    - name: Configure
      run: |
        cat >>.bazelrc.local <<EOF
        common --config=ci
        EOF
