name: Set up GitHub runner

inputs:
  github_token:
    type: string

runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        github-token: ${{ inputs.github_token }}
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Configure
      shell: bash
      run: |
        cat >>.bazelrc.local <<EOF
        common --config=ci
        EOF
    - name: Configure MacOS
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        cat >>.bazelrc.local <<EOF
        common --config=macos_ci
        EOF
