name: Set up GitHub runner

inputs:
  github_token:
    type: string

runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      with:
        github-token: ${{ inputs.github_token }}
    - uses: DeterminateSystems/magic-nix-cache-action@84c0677f58dcedf3b91f8223ce36a9ea5b3c84b7 # v15
    - run: 'nix --version'
      shell: bash
    - name: Configure
      shell: bash
      run: |
        cat >>.bazelrc.local <<EOF
        common --config=ci
        EOF
    - name: Configure MacOS
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        cat >>.bazelrc.local <<EOF
        common --config=macos_ci
        EOF
