name: Set up GitHub runner

inputs:
  github_token:
    type: string

runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      with:
        github-token: ${{ inputs.github_token }}
    - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
    - run: 'nix --version'
      shell: bash
    - name: Configure
      shell: bash
      run: |
        cat >>.bazelrc.local <<EOF
        common --config=ci
        EOF
    - name: Configure MacOS
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        cat >>.bazelrc.local <<EOF
        common --config=macos_ci
        EOF
