name: Set up GitHub runner

inputs:
  github_token:
    type: string

runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      with:
        github-token: ${{ inputs.github_token }}
    - uses: DeterminateSystems/magic-nix-cache-action@e1c1dae8e170ed20fd2e6aaf9979ca2d3905d636 # v12
    - run: 'nix --version'
      shell: bash
    - name: Configure
      shell: bash
      run: |
        cat >>.bazelrc.local <<EOF
        common --config=ci
        EOF
    - name: Configure MacOS
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        cat >>.bazelrc.local <<EOF
        common --config=macos_ci
        EOF
