#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

fail() {
  echo >&2 "$@"
  exit 1
}

ghc_version="${RNS_GHC_VERSION:-}"

while (("$#")); do
  case "${1}" in
    "--ghc-version")
      ghc_version="${2}"
      shift 2
      ;;
    *)
      if [[ -z "${script:-}" ]]; then
        script="${1}"
        shift 1
      else
        fail "Unexpected argument:" "${1}"
      fi
      ;;
  esac
done

if [[ -z "${script:-}" ]]; then
  fail "A script for a path to a file must be provided."
fi

cmd=( nix-shell --arg docTools false --pure )
if [[ -n "${ghc_version:-}" ]]; then
  cmd+=( --argstr ghcVersion "${ghc_version}" )
fi
cmd+=( --run "${script}" )
"${cmd[@]}"
